#############################################################################
###
### Hosts & roles
###

- hosts:         all
  remote_user:   opc
  become:        true
  become_user:   root
  become_method: sudo
  gather_facts:  true

  roles:
    - common
      # install generic packages
      #when:
      #  # - inventory_hostname in groups['cicd']
      #  - ('cicd' in group_names)
